"""Markdown export builders for Pilot Control Center / feedback review exports.

Pure formatting only: every function here takes data the caller already
fetched from ``WorkspaceStore`` (the feedback_report snapshot, or
``get_pilot_conversation_detail`` results) and returns a single markdown
string. Nothing in this module opens a database connection, calls the
analyst runtime, or calls an LLM/provider -- it is deterministic string
building over already-persisted, already-safe-allowlisted data.

Design notes on embedded content
---------------------------------
- Message/comment text is NEVER HTML-escaped: escaping would make quoted
  Markdown/code fences unreadable to a human reviewer opening the file.
- Document structure (headings, horizontal rules) is generated by us and
  never derived from message content, so a message that itself contains
  ``#`` headings, code fences, or ``---`` lines cannot alter the shape of
  the surrounding document -- every section is delimited the same way
  regardless of what is inside it.
- Only fields already vetted by ``tools.analyst_workspace.store``'s
  ``_SAFE_TECHNICAL_CONTEXT_KEYS`` allowlist (surfaced here as plain dicts)
  are ever rendered as "diagnostics" -- this module never spreads an
  arbitrary dict or dataclass into the document.
"""
from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

_HR = "\n\n---\n\n"

_RATING_LABEL = {"up": "\U0001F44D up", "down": "\U0001F44E down"}


def _timestamp_for_filename(now: datetime | None = None) -> str:
    return (now or datetime.now(UTC)).strftime("%Y-%m-%d_%H%M")


def feedback_export_filename(now: datetime | None = None) -> str:
    return f"toesca_pilot_feedback_{_timestamp_for_filename(now)}.md"


def conversations_export_filename(now: datetime | None = None) -> str:
    return f"toesca_pilot_conversations_{_timestamp_for_filename(now)}.md"


def _fmt(value: Any) -> str:
    if value is None:
        return "_(ausente)_"
    if isinstance(value, bool):
        return "sí" if value else "no"
    return str(value)


def _rating_label(rating: str | None) -> str:
    return _RATING_LABEL.get(rating or "", "sin calificar")


def _diagnostics_block(diagnostics: dict[str, Any] | None) -> str:
    """Render only the allowlisted keys already present on ``diagnostics``.

    Never spreads an arbitrary dict -- the caller is responsible for having
    passed only the output of the store's safe-allowlist helpers
    (``_safe_turn_diagnostics`` / feedback_report.technical_context).
    """
    if not diagnostics:
        return "_(sin telemetría)_"
    return "\n".join(f"- **{key}:** {_fmt(value)}" for key, value in diagnostics.items())


def _message_body_block(role_label: str, created_at: Any, content: str, *, extra_meta: str = "") -> str:
    header = f"#### {role_label} — {_fmt(created_at)}{extra_meta}"
    return f"{header}\n\n{content or ''}"


# ── Feedback reports export ─────────────────────────────────────────────────

def build_feedback_reports_export(
    reports: list[dict[str, Any]], *, generated_at: str | None = None,
) -> str:
    """Build ONE markdown document for the given feedback reports.

    Each item in ``reports`` is expected to carry: id, reporter_user_id,
    reporter_display_name, conversation_id, anchor_message_id, comment,
    conversation_snapshot (list of {message_id, role, content, created_at} --
    the immutable snapshot taken at report time), technical_context (the
    already-safe-allowlisted dict, or None), status, created_at, updated_at,
    and live_rating (the CURRENT rating of the anchor message -- "up",
    "down", or None -- which is allowed to differ from what it was at
    report time, since ratings can change after the report was filed).
    """
    generated_at = generated_at or datetime.now(UTC).isoformat(timespec="seconds")
    status_counts: dict[str, int] = {}
    for report in reports:
        status_counts[report["status"]] = status_counts.get(report["status"], 0) + 1

    header_lines = [
        "# Toesca Pilot — Reportes de feedback",
        "",
        f"- **Generado:** {generated_at}",
        f"- **Total reportes:** {len(reports)}",
    ]
    for status in sorted(status_counts):
        header_lines.append(f"- **Estado `{status}`:** {status_counts[status]}")
    header = "\n".join(header_lines)

    sections = [_feedback_report_section(report) for report in reports]
    body = _HR.join(sections) if sections else "_(sin reportes)_"
    return f"{header}{_HR}{body}\n"


def _feedback_report_section(report: dict[str, Any]) -> str:
    lines = [
        f"## Reporte {report['id']}",
        "",
        f"- **Estado:** {report['status']}",
        f"- **Reportado por:** {report['reporter_display_name']} ({report['reporter_user_id']})",
        f"- **Fecha del reporte:** {report['created_at']}",
        f"- **Última actualización:** {report['updated_at']}",
        f"- **Conversación:** {report['conversation_id']}",
        f"- **Mensaje reportado:** {report['anchor_message_id']}",
        f"- **Calificación actual de la respuesta reportada:** {_rating_label(report.get('live_rating'))}",
        "",
        "### Comentario del reportero",
        "",
        report["comment"] or "",
        "",
        "### Conversación al momento del reporte (snapshot inmutable)",
        "",
    ]
    snapshot = report.get("conversation_snapshot") or []
    if snapshot:
        blocks = []
        for message in snapshot:
            role_label = "Usuario" if message.get("role") == "user" else "Asistente"
            extra = " — respuesta reportada" if message.get("message_id") == report["anchor_message_id"] else ""
            blocks.append(_message_body_block(role_label, message.get("created_at"), message.get("content", ""), extra_meta=extra))
        lines.append("\n\n".join(blocks))
    else:
        lines.append("_(sin mensajes)_")
    lines += [
        "",
        "### Diagnóstico técnico (respuesta reportada, solo campos permitidos)",
        "",
        _diagnostics_block(report.get("technical_context")),
    ]
    return "\n".join(lines)


# ── Batch conversation export ───────────────────────────────────────────────

def build_conversations_export(
    conversations: list[dict[str, Any]], *, generated_at: str | None = None,
) -> str:
    """Build ONE markdown document for the given conversations.

    Each item in ``conversations`` is expected to have the shape returned by
    ``WorkspaceStore.get_pilot_conversation_detail`` -- transcript + current
    ratings + report notes + already-safe-allowlisted diagnostics per
    assistant message.
    """
    generated_at = generated_at or datetime.now(UTC).isoformat(timespec="seconds")
    unique_users = {c.get("owner_user_id") for c in conversations}
    user_msg_count = assistant_msg_count = rated_count = up_count = down_count = reported_count = 0
    for conversation in conversations:
        for message in conversation.get("messages", []):
            if message["role"] == "user":
                user_msg_count += 1
                continue
            assistant_msg_count += 1
            rating = message.get("rating")
            if rating == "up":
                up_count += 1
                rated_count += 1
            elif rating == "down":
                down_count += 1
                rated_count += 1
            if message.get("reports"):
                reported_count += 1

    header_lines = [
        "# Toesca Pilot — Conversaciones exportadas",
        "",
        f"- **Generado:** {generated_at}",
        f"- **Conversaciones:** {len(conversations)}",
        f"- **Usuarios distintos:** {len(unique_users)}",
        f"- **Mensajes de usuario:** {user_msg_count}",
        f"- **Respuestas del asistente:** {assistant_msg_count}",
        f"- **Respuestas calificadas:** {rated_count} (\U0001F44D {up_count} · \U0001F44E {down_count})",
        f"- **Respuestas reportadas:** {reported_count}",
    ]
    header = "\n".join(header_lines)

    sections = [_conversation_section(conversation) for conversation in conversations]
    body = _HR.join(sections) if sections else "_(sin conversaciones)_"
    return f"{header}{_HR}{body}\n"


def _conversation_section(conversation: dict[str, Any]) -> str:
    lines = [
        f"## Conversación: {conversation.get('title') or '(sin título)'} ({conversation['id']})",
        "",
        f"- **Usuario:** {conversation.get('owner_display_name')} ({conversation.get('owner_username')})",
        f"- **Creada:** {conversation.get('created_at')}",
        f"- **Última actividad:** {conversation.get('updated_at')}",
        f"- **Archivada:** {_fmt(conversation.get('archived'))}",
        "",
        "### Transcripción",
        "",
    ]
    blocks = []
    for message in conversation.get("messages", []):
        if message["role"] == "user":
            blocks.append(_message_body_block("Usuario", message.get("created_at"), message.get("content", "")))
            continue
        reports = message.get("reports") or []
        reported = "sí" if reports else "no"
        extra = f" — calificación: {_rating_label(message.get('rating'))} — reportado: {reported}"
        block = [_message_body_block("Asistente", message.get("created_at"), message.get("content", ""), extra_meta=extra)]
        if reports:
            block.append("")
            block.append("**Reportes sobre este mensaje:**")
            for report in reports:
                block.append(
                    f"- estado `{report['status']}` por {report['reporter_display_name']} "
                    f"({report['created_at']}): {report['comment']}"
                )
        block.append("")
        block.append("**Diagnóstico técnico (solo campos permitidos):**")
        block.append("")
        block.append(_diagnostics_block(message.get("diagnostics")))
        blocks.append("\n".join(block))
    lines.append("\n\n".join(blocks) if blocks else "_(sin mensajes)_")
    return "\n".join(lines)
